---

- name: Upload license file
  uri:
    url: https://localhost/api/v2/config/
    validate_certs: no
    method: POST
    force_basic_auth: yes
    user: admin
    password: "{{ towerinstall_admin_password }}"
    body: "{{ lookup('file','license.json') }}"
    body_format: json
    headers:
      Content-Type: "application/json"
