---

- name: "[Tower] Download and Extract Tower"
  unarchive:
    src: "{{ towerinstall_tower_releases_url }}/{{ towerinstall_tower_setup_file }}"
    dest: "{{ towerinstall_working_location }}"
    remote_src: yes
    exclude: "inventory"
  register: tower_download_extract

- name: Populate Tower Setup Inventory from Template
  template:
    src: inventory.j2
    dest: "{{ towerinstall_working_location }}/ansible-tower-setup-{{ towerinstall_tower_release_version }}/inventory"

- name: "Run Ansible Tower Setup"
  become: true
  shell: ./setup.sh
  args:
    chdir: "{{ towerinstall_working_location }}/ansible-tower-setup-{{ towerinstall_tower_release_version }}"

- pause:
    minutes: 1
